name = "DumbCompleter"
uuid = "b9d245dc-5d95-11e9-326a-bbd03ea8ebff"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.1.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
